### ISSUE TITLE
Ad extension to Slicer extension manager

### ISSUE THREAD

**Issue by lassoan** [flywheel-apps/SlicerFlywheelConnect#1]
I've come across this extension now. Nice work!

You can make this extension available for Slicer users by submitting it to the [extensions index](https://github.com/Slicer/ExtensionsIndex).

This would increase its visibility for Slicer users and make installation much easier.

**Comment by NPann** [comment]
@lassoan which category do you think our extension (I/O integration with a Flywheel instance) would fit best ? Or should I created a new  one for I/O?

**Comment by lassoan** [comment]
Maybe Informatics or Remote category fits the best. We plan to reorganize the categories in a few months (along with some other extensions manager backend updates) anyway, so most likely this category will change then anyway.

**Comment by lmperry** [comment]
Closing as this was completed. Thanks all!
